### ISSUE TITLE
Provide for a graceful "No code coverage available" scenario

### ISSUE THREAD

**Issue by cooperaj** [matthiasnoback/behat-local-code-coverage-extension#6]
When PHPUnit runs and fails to find a code coverage driver (xdebug) it tells you and continues with the tests anyway. I just doesn't generate the coverage reports. This is pretty good as it simplifies our phpunit config and means we can choose to run with or without coverage by simply not enabling xdebug on that container run. 

But this extension fails hard if a coverage driver cannot be found. Ideally it would provide for the same behaviour as PHPUnit.

**Comment by matthiasnoback** [comment]
Fixed by #7.
