### ISSUE TITLE
Inconsistant coverage reporting compared to PHPUnit

### ISSUE THREAD

**Issue by cooperaj** [matthiasnoback/behat-local-code-coverage-extension#8]
PHPunit, on a test suite that provides 100% coverage of a class gives me 

<img width="402" alt="Screenshot 2020-02-24 16 07 02" src="https://user-images.githubusercontent.com/400210/75169248-1ddfd600-5720-11ea-87c5-febc1110c2d7.png">

Behat coverage, with a suite which *I think* gives 100% coverage gives me

<img width="397" alt="Screenshot 2020-02-24 16 08 17" src="https://user-images.githubusercontent.com/400210/75169312-36e88700-5720-11ea-9227-79edc9b6cc26.png">

or (different method but similar code)

<img width="392" alt="Screenshot 2020-02-24 16 08 32" src="https://user-images.githubusercontent.com/400210/75169327-3c45d180-5720-11ea-9937-949c3ad038a2.png">

The switch case lines are always ignored by phpunit, but intermittently covered by behat-local-code-coverage. I've had a rummage through both PHPunit and this extensions implementation of the CodeCoverage library and they both call in very similar ways. So I have no realy idea why they're behaving differently.

The only difference in the coverage files that I can see is that a PHPUnit file does not have any $ignoredLines when debugging. This extension produces files with $ignoredLines populated.

**Comment by matthiasnoback** [comment]
I have no clue, sorry. I don't know that much about how the coverage library is actually called, IIRC I just looked at how PHPUnit does it ;)
